Packer base
Otus-DevOps-2022-02/Alexander-High_infra pull request #4
Opened 2022-08-20 15:54 UTC by Alexander-High

# Выполнено ДЗ №7

 - [X] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Создан шаблон ubuntu16.json для настройки хоста с предустановленными MongoDB И Ruby.
 - Поведена параметризация шаблона ubuntu16.json переменными yc_folder_id, yc_sa_key_file, yc_subnet_id.
 - Внесены дополнительные опции указатель зоны и объем диска.

## Как запустить проект:
 - Через web-интерфейс YC

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [X] Выставил label с темой домашнего задания

2022-08-24 16:01 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Оставил комментарий к файлу, ошибки скорее всего протекли и в следующий пуллреквест
Исправив этот, вы скорее всего поправите и следующий или какую то его часть =)

2022-08-24 16:01 UTC, mrgreyves commented on packer/ubuntu16.json
> +  		"folder_id": "{{env `YC_FOLDER_ID`}}",
Ошибка как раз и связана с тем что вы берете переменную из переменных окружения =)

2022-08-24 16:01 UTC, mrgreyves commented on packer/ubuntu16.json
> +  		"folder_id": "{{env `YC_FOLDER_ID`}}",
Дополнительно нужно указать ключик сервисного аккаунта =)

2022-08-25 20:39 UTC, Alexander-High commented
Changed files? tetst ok!

2022-08-26 07:09 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все корректно =)

2022-08-27 10:29 UTC, merged